#!/bin/sh
# Thin shim: CC writes a hook-decision JSON to stdin; we POST it to Casa's
# loopback /hooks/resolve endpoint together with the policy name, and echo
# the response back to CC on stdout. CC uses the response to allow/deny
# the tool call.
#
# Usage: hook_proxy.sh <policy_name>
#
# Invoked from .claude/settings.json generated by drivers.hook_bridge.

set -e

POLICY="$1"
if [ -z "$POLICY" ]; then
  echo '{"decision": "block", "reason": "hook_proxy: missing policy arg"}'
  exit 0
fi

PAYLOAD="$(cat)"

# Build the request body with jq so $POLICY is safely encoded regardless of
# special characters, and $PAYLOAD is parsed as JSON (not re-encoded as a
# string). jq is present in the Casa image.
BODY=$(jq -nc --arg p "$POLICY" --argjson pl "$PAYLOAD" \
       '{"policy":$p,"payload":$pl}') || {
  echo '{"decision": "block", "reason": "hook_proxy: malformed payload"}'
  exit 0
}

RESP=$(curl -sf -X POST \
     -H "Content-Type: application/json" \
     --data-binary "$BODY" \
     "http://127.0.0.1:8099/hooks/resolve" 2>&1) || {
  # On any transport error, allow by default — the hook should not block
  # the engagement if Casa is unreachable (fail-open).
  echo '{"decision": "allow", "reason": "hook_proxy: casa unreachable"}'
  exit 0
}

echo "$RESP"
